### PR TITLE
Add cursor controls for player and CPU

### LINKED ISSUE #3: Make Player Follow Cursor

### LINKED ISSUE #4: Make Auto Progress Cursor

### PR DESCRIPTION
**Pull request by mxd1760**
commit 1 Closes #3
commit 2 Closes #4

### CODE REVIEW

**Comment by mxd1760** [comment]
2nd commit closes #4

**Review by Jayman2000 — CHANGES_REQUESTED** [review]
I have a suggestion for how this PR could be improved. Please the fixup commit in [this branch](https://github.com/Jayman2000/song-typing-pr/tree/make-player-follow-cursor-potential-fixup).

**Comment by mxd1760** [comment]
force squashed the fixup! commit
it was ugly

**Review by Jayman2000 — APPROVED** [review]
LGTM.

**Pull request merged**
