### PR TITLE
adding lrc files

### PR DESCRIPTION
**Pull request by mxd1760**

### CODE REVIEW

**Comment by mxd1760** [comment]
this first commit adds the files that can be used to practice reading in lrc data into the game and syncing it with music and stuff. Credit to <lrcgenerator.com> for helping a ton with making the lrc file. if we ever need a tool for users to sync stuff, I think that having it work somewhat like that would be the best.

**Comment by mxd1760** [comment]
I also think that this closes #33

**Comment by mxd1760** [comment]
[this commit](https://github.com/mxd1760/song-typing/pull/39/commits/b87bec322f822fd2c1d6ffb2d0df34905bbd97b0) adds lrc file reading to the repo which closes #31. 

There are still a bunch of things that need to be fixed though
 - the lines now more than ever need to be loaded from something other than a character size
 - the whitespace characters like " " and "\n" need to show up as something in order to help people actually type along

**Review by Jayman2000 — APPROVED** [review]
I tested the LRC file in MPV, and it seemed to work and be accurate. Also, I tried playing the MP3 file in Godot and it worked.

**Pull request merged**
