### PR TITLE
option menu

### LINKED ISSUE #24: Add options menu

### PR DESCRIPTION
**Pull request by mxd1760**
closes #24

### CODE REVIEW

**Comment by mxd1760** [comment]
maybe we could setup the options as an overlay so that they can be changed by spawning and removing the scene rather than loading it. this would make it possible to change options midway through a level instead of needing to restart the level. (we should make sure that we indicate weather or not the changes made could take effect immediately though)

**Review by Jayman2000 — CHANGES_REQUESTED** [review]
It’s mostly good, but I have two suggestions. I pushed fixup commits for the suggestions [here](https://github.com/Jayman2000/song-typing-pr/tree/options_menu_potential_fixup).

**Comment by mxd1760** [comment]
oh I accepted your fixup changes

**Review by Jayman2000 — APPROVED** [review]
I tested the options menu, and it works!

**Pull request merged**
